import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
mkdirSync('packages/shared/abi', { recursive: true });
for (const contract of ['FanPotCampaign', 'FanPotFactory']) {
  const artifact = JSON.parse(readFileSync(`packages/contracts/out/${contract}.sol/${contract}.json`, 'utf8'));
  writeFileSync(`packages/shared/abi/${contract}.json`, JSON.stringify(artifact.abi, null, 2) + '\n');
  writeFileSync(`packages/shared/abi/${contract}.ts`, `// Generated by pnpm abi; do not edit.\nexport const ${contract[0].toLowerCase() + contract.slice(1)}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`);
}
